srpms-docker:
	echo "TEST TEST TEST TEST"
	make -C ../../ -f Makefile.pkgname PKG_NAME=forgeupgrade buildsrc
	make -C ../../ -f Makefile.pkgname PKG_NAME=jpgraph-tuleap buildsrc
	make -C ../../ -f Makefile.pkgname PKG_NAME=viewvc-tuleap buildsrc
	make -C ../../ -f Makefile.pkgname PKG_NAME=htmlpurifier buildsrc
	make -C ../../ -f Makefile.pkgname PKG_NAME=php-zendframework buildsrc
	make -C ../../ -f Makefile.pkgname PKG_NAME=php-restler buildsrc
	make -C ../../ -f Makefile.pkgname PKG_NAME=restler-api-explorer buildsrc
	ls -al /root/rpmbuild/*

